export const glossary = {
    glossary: {
        reyno: "Denominación histórica del Reino de Navarra, escrita con 'y' griega para honrar la grafía medieval. El Reyno de Navarra existió como entidad política independiente desde el siglo IX hasta 1512, cuando fue anexionado por la Corona de Castilla, aunque mantuvo sus instituciones y fueros propios hasta el siglo XIX.",
        fueros: "Conjunto de leyes, privilegios y libertades propias del Reino de Navarra, pactadas entre el rey y el pueblo navarro. Los Fueros garantizaban derechos y autonomía locales únicos en la Península Ibérica. Navarra conservó sus Fueros durante siglos tras la unión con Castilla, hasta la Ley Paccionada de 1841.",
        merindad: "División administrativa del Reino de Navarra, equivalente a una provincia. El reino se dividía en cinco merindades: Pamplona, Estella, Tudela, Sangüesa y Olite. Cada merindad estaba gobernada por un Merino, oficial real encargado de la administración, justicia y recaudación.",
        burgo: "Barrio o núcleo de población habitado principalmente por francos (inmigrantes del norte de los Pirineos) en las ciudades medievales navarras. Los burgos se diferenciaban de los barrios de navarros y judíos, teniendo sus propias leyes y fueros. Estella estaba formada por varios burgos distintos.",
        crismon: "Monograma de Cristo formado por las letras griegas Ji (Χ) y Rho (Ρ), las dos primeras de 'Χριστός' (Cristo). Símbolo cristiano de victoria y protección muy frecuente en el arte románico navarro. Aparece en portadas y capiteles de iglesias del Camino de Santiago.",
        cadenas: "Las cadenas del escudo de Navarra hacen referencia a los hierros del campamento del califa almohade Muhammad al-Nasir, que Sancho VII el Fuerte rompió en la Batalla de las Navas de Tolosa (1212). Esta gesta épica quedó inmortalizada en el escudo del reino como símbolo de valentía y victoria.",
        camino: "La Ruta Jacobea o Camino de Santiago es la red de rutas de peregrinación que desde toda Europa conducen hasta la tumba del Apóstol Santiago en Santiago de Compostela. Navarra fue la principal puerta de entrada a la Península Ibérica, y ciudades como Roncesvalles, Pamplona y Estella deben gran parte de su historia al Camino.",
        peregrino: "Viajero que hacía el Camino de Santiago por motivos religiosos. En la Edad Media, miles de peregrinos cruzaban Navarra cada año, impulsando la economía, el arte románico y la cultura del reino. Se identificaban por el bastón, la esclavina y la concha de vieira.",
        facciones: "Las dos grandes facciones nobiliarias que dividieron el Reino de Navarra en el siglo XV desgastando al reino hasta hacerlo vulnerable. Los Agramonteses apoyaban a los Aragón, y los Beaumonteses a los Foix. Su guerra civil interna facilitó la conquista de Fernando el Católico en 1512.",
        jus_castillo: "Nombre de la iglesia de Estella construida sobre la antigua Sinagoga de Elgacena. En 1145, el rey García Ramírez el Restaurador cedió la sinagoga judía al obispo de Pamplona para convertirla en iglesia cristiana. Es un testimonio único de la coexistencia y los conflictos entre las tres culturas medievales de Navarra.",
        sinagoga: "La Sinagoga de Elgacena fue la primera y más antigua sinagoga del Reino de Navarra, fundada en el siglo XI en Estella. En 1145 fue convertida en iglesia cristiana (Santa María Jus del Castillo) tras el traslado de la judería. Su transformación refleja la compleja relación entre las comunidades cristiana, judía y musulmana del Reyno.",
        romanico: "Estilo artístico y arquitectónico que floreció en Europa Occidental entre los siglos XI y XIII. Navarra posee uno de los patrimonios románicos más ricos de Europa, concentrado especialmente en las ciudades del Camino de Santiago. Se caracteriza por arcos de medio punto, muros gruesos, bóvedas de cañón y una rica escultura en capiteles y portadas.",
        infanzon: "Miembro de la baja nobleza navarra, por debajo de los ricoshombres. Los infanzones tenían privilegios nobiliarios pero sin títulos ni grandes señoríos. Su existencia reflejaba la complejidad del sistema feudal navarro, donde la nobleza estaba muy estratificada.",
        almirante: "Alto cargo naval y militar del Reino de Navarra, encargado de las fuerzas fluviales y, en ocasiones, de la diplomacia. Navarra, aunque sin costa marítima directa, tenía intereses comerciales y navegables a través del Ebro y sus afluentes.",
        javierada: "Peregrinación popular que cada año en marzo recorre los 20 kilómetros entre Sangüesa y el Castillo de Javier, en honor a San Francisco Javier, Patrón de Navarra. Con decenas de miles de participantes, es la mayor peregrinación de Navarra y una de las más importantes de España.",
        navas: "La Batalla de las Navas de Tolosa (1212) fue uno de los enfrentamientos más decisivos de la Reconquista. Los reyes de Castilla, Aragón y Navarra, junto con cruzados europeos, derrotaron al ejército almohade del califa Muhammad al-Nasir. La participación heroica de Sancho VII el Fuerte de Navarra quedó inmortalizada en el escudo del reino."
    }
};
